from flask import Flask
from flask_restful import Resource, Api
from flask_httpauth import HTTPBasicAuth
from src.system import System
from src.user_model import UserModel
from src.subject import SubjectModel
from src.group_model import GroupModel

app = Flask(__name__)
app.secret_key = "not a secret"
api = Api(app)
auth = HTTPBasicAuth()

system = System()
user = UserModel("first", "last", "tester", "password")
user.add_subject(SubjectModel("HUMS1008", "FL"))
user.add_subject(SubjectModel("FINS3630", "ON"))
user.add_subject(SubjectModel("BIOM9650", "ON"))

user = UserModel("Chi", "Sandrock", "tester1", "password")
user.add_subject(SubjectModel("EDST6765", "CR"))
user.add_subject(SubjectModel("LAWS3301", "PS"))
user.add_subject(SubjectModel("CHEM3021", "PS"))
system.add_user(user)
user = UserModel("Danuta", "Gillum", "tester2", "password")
user.add_subject(SubjectModel("GENM0703", "HD"))
user.add_subject(SubjectModel("HESC2452", "FL"))
user.add_subject(SubjectModel("MGMT4501", "CR"))
system.add_user(user)
user = UserModel("Jeniffer", "Roden", "tester3", "password")
user.add_subject(SubjectModel("BIOM9410", "DN"))
user.add_subject(SubjectModel("FOOD1120", "FL"))
user.add_subject(SubjectModel("ZEIT4118", "FL"))
system.add_user(user)
user = UserModel("Reinaldo", "Leduc", "tester4", "password")
user.add_subject(SubjectModel("LAWS3187", "DN"))
user.add_subject(SubjectModel("BIOM5940", "CR"))
user.add_subject(SubjectModel("EDST1108", "PS"))
system.add_user(user)
user = UserModel("Marlana", "Mcclure", "tester5", "password")
user.add_subject(SubjectModel("INOV2110", "DN"))
user.add_subject(SubjectModel("ATSI2011", "ON"))
user.add_subject(SubjectModel("ARTS2021", "DN"))
system.add_user(user)
user = UserModel("Danuta", "Joynt", "tester6", "password")
user.add_subject(SubjectModel("MGMT4103", "FL"))
user.add_subject(SubjectModel("ARTS2846", "CR"))
user.add_subject(SubjectModel("PLAN2002", "HD"))
system.add_user(user)
user = UserModel("Betsy", "Fenn", "tester7", "password")
user.add_subject(SubjectModel("EDST6701", "FL"))
user.add_subject(SubjectModel("MINE4250", "FL"))
user.add_subject(SubjectModel("SOLA3020", "PS"))
system.add_user(user)
user = UserModel("Reanna", "Cook", "tester8", "password")
user.add_subject(SubjectModel("MUSC2803", "ON"))
user.add_subject(SubjectModel("NANO3001", "ON"))
user.add_subject(SubjectModel("COMP3431", "FL"))
system.add_user(user)
user = UserModel("Lavina", "Koerner", "tester9", "password")
user.add_subject(SubjectModel("ZEIT2207", "CR"))
user.add_subject(SubjectModel("ZBUS1102", "FL"))
user.add_subject(SubjectModel("MTRN4230", "HD"))
system.add_user(user)
user = UserModel("Jama", "Rushing", "tester10", "password")
user.add_subject(SubjectModel("CHEM3901", "HD"))
user.add_subject(SubjectModel("BLDG2013", "CR"))
user.add_subject(SubjectModel("ARTS3664", "PS"))
system.add_user(user)
user = UserModel("Maxine", "Reiher", "tester11", "password")
user.add_subject(SubjectModel("ZEIT4802", "FL"))
user.add_subject(SubjectModel("ECON3125", "HD"))
user.add_subject(SubjectModel("SAHT1211", "CR"))
system.add_user(user)
user = UserModel("Jama", "Mcguffin", "tester12", "password")
user.add_subject(SubjectModel("OPTM3201", "CR"))
user.add_subject(SubjectModel("SOCW2009", "ON"))
user.add_subject(SubjectModel("YMED1006", "ON"))
system.add_user(user)
user = UserModel("Magali", "Weinmann", "tester13", "password")
user.add_subject(SubjectModel("MARK2085", "DN"))
user.add_subject(SubjectModel("CVEN4031", "ON"))
user.add_subject(SubjectModel("ARTS4608", "FL"))
system.add_user(user)
user = UserModel("Neoma", "Abreu", "tester14", "password")
user.add_subject(SubjectModel("BIOS2061", "ON"))
user.add_subject(SubjectModel("ARTS2384", "HD"))
user.add_subject(SubjectModel("LAWS2326", "FL"))
system.add_user(user)
user = UserModel("Cordell", "Monterrosa", "tester15", "password")
user.add_subject(SubjectModel("COMP4128", "CR"))
user.add_subject(SubjectModel("LAWS3165", "CR"))
user.add_subject(SubjectModel("BABS3021", "FL"))
system.add_user(user)
user = UserModel("Reinaldo", "Rolf", "tester16", "password")
user.add_subject(SubjectModel("VISN1211", "CR"))
user.add_subject(SubjectModel("MDIA4003", "PS"))
user.add_subject(SubjectModel("BEIL0013", "FL"))
system.add_user(user)
user = UserModel("Lyn", "Coletti", "tester17", "password")
user.add_subject(SubjectModel("PLAN4003", "CR"))
user.add_subject(SubjectModel("ZEIT3119", "PS"))
user.add_subject(SubjectModel("COMP4931", "DN"))
system.add_user(user)
user = UserModel("Jama", "Rushing", "tester18", "password")
user.add_subject(SubjectModel("GMAT9606", "ON"))
user.add_subject(SubjectModel("FINS3634", "PS"))
user.add_subject(SubjectModel("EDST6727", "PS"))
system.add_user(user)
user = UserModel("Tinisha", "Reiher", "tester19", "password")
user.add_subject(SubjectModel("ZHSS3201", "HD"))
user.add_subject(SubjectModel("ARTS4706", "FL"))
user.add_subject(SubjectModel("BABS3151", "DN"))
system.add_user(user)
user = UserModel("Cordell", "Reiher", "tester20", "password")
user.add_subject(SubjectModel("PHYS3113", "DN"))
user.add_subject(SubjectModel("ZEIT4114", "FL"))
user.add_subject(SubjectModel("CHEM4003", "PS"))
system.add_user(user)
group = GroupModel("1", "Group Randall", "Location", "Usu an wisi interpretaris, ei dicat dicant mea. Splendide efficiendi inciderint ea vim, pri amet erant partiendo in. Inermis ocurreret pro at, docendi inciderint ea mei. Te cum homero omnium, per in etiam libris oblique, his tamquam appellantur ex. Vim ut blandit copiosae mediocrem, volumus voluptua adversarium cu eum, ea legere audire mel.", ['ATSI0001', 'HESC3592', 'SOCW1001'], 63643534234, "tester17", 25, 3)
system.add_group(group)
group.add_user("tester5")
group.add_user("tester13")
group = GroupModel("2", "Group Neoma", "Location", "Regione accumsan tacimates id vel, vix et probo decore. Elit legimus fuisset pri at. Vix nibh utamur prodesset ea, ad aliquid facilisi sed, eum dicat assueverit ad. Sea ei volutpat pertinacia, vis te veniam apeirian imperdiet, nam ex ullum cetero luptatum. Mel audire eligendi te. No eum tota definiebas definitionem.", ['PLAN3041', 'ARTS3690', 'MUSC3806'], 63643534234, "tester11", 5, 2)
system.add_group(group)
group.add_user("tester9")
group.add_user("tester11")
group = GroupModel("3", "Group Reinaldo", "Location", "Aliquip iuvaret utroque sed an, vitae graeco voluptaria quo et. Ad iudico mucius quo. Legimus efficiendi eu nec, utroque vulputate ad usu. Mucius facilis ex qui, te quis accusam mel, numquam consectetuer qui ad. Qui iudico platonem te.", ['ARTS3013', 'ELEC2117', 'INFS3830'], 63643534234, "tester3", 5, 2)
system.add_group(group)
group.add_user("tester16")
group.add_user("tester13")
group = GroupModel("4", "Group Maxine", "Location", "Est te sanctus placerat eleifend, eam ad legere vituperata accommodare. Te his aeque oporteat corrumpit, has ei noster argumentum. Augue laudem scribentur vel at, eu nisl iudico nusquam quo. Nulla paulo ea per, inermis sadipscing mel ea. An fabulas accusamus ius, ex integre theophrastus sit, ei magna nonumes pro.", ['SART2403', 'COMP6752', 'PTRL2030'], 63643534234, "tester8", 20, 3)
system.add_group(group)
group.add_user("tester9")
group.add_user("tester17")
group = GroupModel("5", "Group Pok", "Location", "Ex iriure nostrum comprehensam sit. Cu cum natum detracto definitiones, meis intellegat elaboraret cu vix. Vim in eirmod partiendo, homero mediocrem reprimique usu et. Vero mutat interpretaris ut nec, oratio mnesarchum omittantur id mei, vel tation ridens adversarium in. Cu clita tempor postea pro. Nam ut dolores persequeris. Animal omittam ut nec.", ['ZEIT4401', 'TABL3757', 'ARTS2248'], 63643534234, "tester20", 5, 3)
system.add_group(group)
group.add_user("tester3")
group.add_user("tester20")
group = GroupModel("6", "Group Lyn", "Location", "In congue delenit splendide mea. Vis probo prompta et, an dignissim mnesarchum eos. Et dicit omnesque postulant nam, habeo delectus eos id, duo movet rationibus in. Eum torquatos assentior instructior te. Eirmod mnesarchum est ad, in purto docendi his. Minim perpetua eos ei, ne tollit percipit pro, ea vel clita decore deterruisset.", ['MTRN4110', 'CEIC3005', 'ARTS2698'], 63643534234, "tester10", 15, 3)
system.add_group(group)
group.add_user("tester6")
group.add_user("tester10")
group = GroupModel("7", "Group Gaynell", "Location", "Usu an wisi interpretaris, ei dicat dicant mea. Splendide efficiendi inciderint ea vim, pri amet erant partiendo in. Inermis ocurreret pro at, docendi inciderint ea mei. Te cum homero omnium, per in etiam libris oblique, his tamquam appellantur ex. Vim ut blandit copiosae mediocrem, volumus voluptua adversarium cu eum, ea legere audire mel.", ['PLAN1052', 'BEIL0001', 'CVEN3402'], 63643534234, "tester11", 20, 2)
system.add_group(group)
group.add_user("tester19")
group.add_user("tester13")
group = GroupModel("8", "Group Reinaldo", "Location", "Est te sanctus placerat eleifend, eam ad legere vituperata accommodare. Te his aeque oporteat corrumpit, has ei noster argumentum. Augue laudem scribentur vel at, eu nisl iudico nusquam quo. Nulla paulo ea per, inermis sadipscing mel ea. An fabulas accusamus ius, ex integre theophrastus sit, ei magna nonumes pro.", ['CODE1210', 'NEUR3121', 'NAVL3410'], 63643534234, "tester1", 20, 2)
system.add_group(group)
group.add_user("tester16")
group.add_user("tester18")
group = GroupModel("9", "Group China", "Location", "Regione accumsan tacimates id vel, vix et probo decore. Elit legimus fuisset pri at. Vix nibh utamur prodesset ea, ad aliquid facilisi sed, eum dicat assueverit ad. Sea ei volutpat pertinacia, vis te veniam apeirian imperdiet, nam ex ullum cetero luptatum. Mel audire eligendi te. No eum tota definiebas definitionem.", ['HESC4611', 'AERO4110', 'BEES5041'], 63643534234, "tester11", 5, 2)
system.add_group(group)
group.add_user("tester3")
group.add_user("tester3")
group = GroupModel("10", "Group Regan", "Location", "Agam elitr eos ea. Viderer detraxit mei in, te ferri lobortis reprehendunt per. Vel ex quando graecis apeirian, amet eius quo ea, quas ceteros mel no. Mei eu lorem ullum.", ['CVEN4003', 'LAWS3251', 'MECH4880'], 63643534234, "tester17", 25, 3)
system.add_group(group)
group.add_user("tester15")
group.add_user("tester5")
group = GroupModel("11", "Group Reanna", "Location", "Ex iriure nostrum comprehensam sit. Cu cum natum detracto definitiones, meis intellegat elaboraret cu vix. Vim in eirmod partiendo, homero mediocrem reprimique usu et. Vero mutat interpretaris ut nec, oratio mnesarchum omittantur id mei, vel tation ridens adversarium in. Cu clita tempor postea pro. Nam ut dolores persequeris. Animal omittam ut nec.", ['ACCT3303', 'ARTS3095', 'MICR3061'], 63643534234, "tester15", 20, 1)
system.add_group(group)
group.add_user("tester20")
group.add_user("tester14")
group = GroupModel("12", "Group Marlana", "Location", "Ex iriure nostrum comprehensam sit. Cu cum natum detracto definitiones, meis intellegat elaboraret cu vix. Vim in eirmod partiendo, homero mediocrem reprimique usu et. Vero mutat interpretaris ut nec, oratio mnesarchum omittantur id mei, vel tation ridens adversarium in. Cu clita tempor postea pro. Nam ut dolores persequeris. Animal omittam ut nec.", ['ARTS2663', 'CHEM1831', 'SCIF1111'], 63643534234, "tester9", 15, 1)
system.add_group(group)
group.add_user("tester8")
group.add_user("tester6")
group = GroupModel("13", "Group Jama", "Location", "Agam elitr eos ea. Viderer detraxit mei in, te ferri lobortis reprehendunt per. Vel ex quando graecis apeirian, amet eius quo ea, quas ceteros mel no. Mei eu lorem ullum.", ['BIOC4318', 'SDES6750', 'ARTS4623'], 63643534234, "tester13", 5, 3)
system.add_group(group)
group.add_user("tester10")
group.add_user("tester18")
group = GroupModel("14", "Group Freddie", "Location", "Has mucius meliore percipitur cu, ut vix soluta malorum scripserit. An sit antiopam accommodare, tamquam salutandi liberavisse quo ex. Utroque oportere at ius, vocent nostrud te sit. Te usu soleat voluptua consectetuer. Duo id simul corpora, sed choro perfecto ex, pri id quem alienum.", ['ZEIT4704', 'ZPEM1502', 'ZPEM3213'], 63643534234, "tester7", 10, 1)
system.add_group(group)
group.add_user("tester19")
group.add_user("tester5")
group = GroupModel("15", "Group Regan", "Location", "Regione accumsan tacimates id vel, vix et probo decore. Elit legimus fuisset pri at. Vix nibh utamur prodesset ea, ad aliquid facilisi sed, eum dicat assueverit ad. Sea ei volutpat pertinacia, vis te veniam apeirian imperdiet, nam ex ullum cetero luptatum. Mel audire eligendi te. No eum tota definiebas definitionem.", ['ELEC1112', 'SENG4904', 'MDIA3010'], 63643534234, "tester12", 5, 3)
system.add_group(group)
group.add_user("tester7")
group.add_user("tester3")
group = GroupModel("16", "Group Betsy", "Location", "Ex iriure nostrum comprehensam sit. Cu cum natum detracto definitiones, meis intellegat elaboraret cu vix. Vim in eirmod partiendo, homero mediocrem reprimique usu et. Vero mutat interpretaris ut nec, oratio mnesarchum omittantur id mei, vel tation ridens adversarium in. Cu clita tempor postea pro. Nam ut dolores persequeris. Animal omittam ut nec.", ['MARK3054', 'MATS4007', 'LAND1482'], 63643534234, "tester11", 20, 2)
system.add_group(group)
group.add_user("tester12")
group.add_user("tester11")
group = GroupModel("17", "Group Jama", "Location", "Reque ubique feugait eu sit. Duo deleniti apeirian partiendo te, an putent expetenda similique mei, usu accumsan disputationi no. Mea fugit affert ei, et omnis justo aliquid sed. No rebum laboramus sit. Pri laudem labore utroque eu, ad oratio nullam detraxit vix.", ['LAWS3192', 'ARTS3750', 'ARTS2452'], 63643534234, "tester15", 20, 3)
system.add_group(group)
group.add_user("tester21")
group.add_user("tester4")
group = GroupModel("18", "Group Booker", "Location", "Est te sanctus placerat eleifend, eam ad legere vituperata accommodare. Te his aeque oporteat corrumpit, has ei noster argumentum. Augue laudem scribentur vel at, eu nisl iudico nusquam quo. Nulla paulo ea per, inermis sadipscing mel ea. An fabulas accusamus ius, ex integre theophrastus sit, ei magna nonumes pro.", ['BLDG3023', 'EDST1104', 'CODE2256'], 63643534234, "tester8", 10, 1)
system.add_group(group)
group.add_user("tester12")
group.add_user("tester2")
group = GroupModel("19", "Group Inell", "Location", "Agam elitr eos ea. Viderer detraxit mei in, te ferri lobortis reprehendunt per. Vel ex quando graecis apeirian, amet eius quo ea, quas ceteros mel no. Mei eu lorem ullum.", ['ZEIT3406', 'ACCT2507', 'LAND2142'], 63643534234, "tester20", 25, 1)
system.add_group(group)
group.add_user("tester17")
group.add_user("tester15")
group = GroupModel("20", "Group Booker", "Location", "Aliquip iuvaret utroque sed an, vitae graeco voluptaria quo et. Ad iudico mucius quo. Legimus efficiendi eu nec, utroque vulputate ad usu. Mucius facilis ex qui, te quis accusam mel, numquam consectetuer qui ad. Qui iudico platonem te.", ['ARTS1782', 'BIOS3221', 'FOOD3030'], 63643534234, "tester18", 20, 2)
system.add_group(group)
group.add_user("tester10")
group.add_user("tester13")
group = GroupModel("21", "Group Talia", "Location", "Usu an wisi interpretaris, ei dicat dicant mea. Splendide efficiendi inciderint ea vim, pri amet erant partiendo in. Inermis ocurreret pro at, docendi inciderint ea mei. Te cum homero omnium, per in etiam libris oblique, his tamquam appellantur ex. Vim ut blandit copiosae mediocrem, volumus voluptua adversarium cu eum, ea legere audire mel.", ['BABS1201', 'SENG2011', 'ENGG1811'], 63643534234, "tester8", 25, 2)
system.add_group(group)
group.add_user("tester4")
group.add_user("tester15")
group = GroupModel("22", "Group Mica", "Location", "Reque ubique feugait eu sit. Duo deleniti apeirian partiendo te, an putent expetenda similique mei, usu accumsan disputationi no. Mea fugit affert ei, et omnis justo aliquid sed. No rebum laboramus sit. Pri laudem labore utroque eu, ad oratio nullam detraxit vix.", ['BIOS3671', 'ZPEM3213', 'INFS2603'], 63643534234, "tester15", 15, 2)
system.add_group(group)
group.add_user("tester4")
group.add_user("tester14")
group = GroupModel("23", "Group Stacie", "Location", "Usu an wisi interpretaris, ei dicat dicant mea. Splendide efficiendi inciderint ea vim, pri amet erant partiendo in. Inermis ocurreret pro at, docendi inciderint ea mei. Te cum homero omnium, per in etiam libris oblique, his tamquam appellantur ex. Vim ut blandit copiosae mediocrem, volumus voluptua adversarium cu eum, ea legere audire mel.", ['PHTN3117', 'ARTS4201', 'AVIA3401'], 63643534234, "tester5", 15, 2)
system.add_group(group)
group.add_user("tester16")
group.add_user("tester1")
group = GroupModel("24", "Group Freddie", "Location", "Regione accumsan tacimates id vel, vix et probo decore. Elit legimus fuisset pri at. Vix nibh utamur prodesset ea, ad aliquid facilisi sed, eum dicat assueverit ad. Sea ei volutpat pertinacia, vis te veniam apeirian imperdiet, nam ex ullum cetero luptatum. Mel audire eligendi te. No eum tota definiebas definitionem.", ['ARCH1121', 'ZEIT4226', 'CVEN3701'], 63643534234, "tester16", 5, 2)
system.add_group(group)
group.add_user("tester2")
group.add_user("tester6")
group = GroupModel("25", "Group Booker", "Location", "Regione accumsan tacimates id vel, vix et probo decore. Elit legimus fuisset pri at. Vix nibh utamur prodesset ea, ad aliquid facilisi sed, eum dicat assueverit ad. Sea ei volutpat pertinacia, vis te veniam apeirian imperdiet, nam ex ullum cetero luptatum. Mel audire eligendi te. No eum tota definiebas definitionem.", ['ZEIT4229', 'FINS3634', 'GENC6007'], 63643534234, "tester6", 25, 3)
system.add_group(group)
group.add_user("tester8")
group.add_user("tester12")
group = GroupModel("26", "Group China", "Location", "Aliquip iuvaret utroque sed an, vitae graeco voluptaria quo et. Ad iudico mucius quo. Legimus efficiendi eu nec, utroque vulputate ad usu. Mucius facilis ex qui, te quis accusam mel, numquam consectetuer qui ad. Qui iudico platonem te.", ['LAWS9801', 'INFS3303', 'ARTS3067'], 63643534234, "tester9", 5, 1)
system.add_group(group)
group.add_user("tester13")
group.add_user("tester3")
group = GroupModel("27", "Group Jacquelyn", "Location", "Reque ubique feugait eu sit. Duo deleniti apeirian partiendo te, an putent expetenda similique mei, usu accumsan disputationi no. Mea fugit affert ei, et omnis justo aliquid sed. No rebum laboramus sit. Pri laudem labore utroque eu, ad oratio nullam detraxit vix.", ['ECON2322', 'ZPEM1303', 'ATSI0002'], 63643534234, "tester5", 15, 3)
system.add_group(group)
group.add_user("tester10")
group.add_user("tester10")
group = GroupModel("28", "Group Talia", "Location", "Lorem ipsum dolor sit amet, legendos instructior ius in, quidam tritani labores duo an. Amet blandit elaboraret no vel, sed in homero invenire efficiantur. Ei vix utamur nostrum. Ex alia voluptua senserit pro.", ['LAWS3251', 'MGMT2704', 'CVEN4310'], 63643534234, "tester19", 15, 3)
system.add_group(group)
group.add_user("tester4")
group.add_user("tester3")
group = GroupModel("29", "Group Maxine", "Location", "Regione accumsan tacimates id vel, vix et probo decore. Elit legimus fuisset pri at. Vix nibh utamur prodesset ea, ad aliquid facilisi sed, eum dicat assueverit ad. Sea ei volutpat pertinacia, vis te veniam apeirian imperdiet, nam ex ullum cetero luptatum. Mel audire eligendi te. No eum tota definiebas definitionem.", ['ZHSS2410', 'MATH1251', 'MFAC4503'], 63643534234, "tester13", 25, 1)
system.add_group(group)
group.add_user("tester18")
group.add_user("tester8")
group = GroupModel("30", "Group China", "Location", "Regione accumsan tacimates id vel, vix et probo decore. Elit legimus fuisset pri at. Vix nibh utamur prodesset ea, ad aliquid facilisi sed, eum dicat assueverit ad. Sea ei volutpat pertinacia, vis te veniam apeirian imperdiet, nam ex ullum cetero luptatum. Mel audire eligendi te. No eum tota definiebas definitionem.", ['EDST2062', 'ZEIT3101', 'ARTS4816'], 63643534234, "tester20", 20, 3)
system.add_group(group)
group.add_user("tester6")
group.add_user("tester1")
group = GroupModel("31", "Group Thresa", "Location", "Lorem ipsum dolor sit amet, legendos instructior ius in, quidam tritani labores duo an. Amet blandit elaboraret no vel, sed in homero invenire efficiantur. Ei vix utamur nostrum. Ex alia voluptua senserit pro.", ['SOMA2818', 'TABL3752', 'BIOT3081'], 63643534234, "tester5", 15, 2)
system.add_group(group)
group.add_user("tester8")
group.add_user("tester5")
group = GroupModel("32", "Group Christal", "Location", "Regione accumsan tacimates id vel, vix et probo decore. Elit legimus fuisset pri at. Vix nibh utamur prodesset ea, ad aliquid facilisi sed, eum dicat assueverit ad. Sea ei volutpat pertinacia, vis te veniam apeirian imperdiet, nam ex ullum cetero luptatum. Mel audire eligendi te. No eum tota definiebas definitionem.", ['EDST6724', 'OPTM5171', 'ARTS1780'], 63643534234, "tester18", 15, 2)
system.add_group(group)
group.add_user("tester16")
group.add_user("tester8")
group = GroupModel("33", "Group Fausto", "Location", "Usu an wisi interpretaris, ei dicat dicant mea. Splendide efficiendi inciderint ea vim, pri amet erant partiendo in. Inermis ocurreret pro at, docendi inciderint ea mei. Te cum homero omnium, per in etiam libris oblique, his tamquam appellantur ex. Vim ut blandit copiosae mediocrem, volumus voluptua adversarium cu eum, ea legere audire mel.", ['SAHT6700', 'BENV2409', 'ARTS1453'], 63643534234, "tester16", 25, 1)
system.add_group(group)
group.add_user("tester8")
group.add_user("tester20")
group = GroupModel("34", "Group Pok", "Location", "Regione accumsan tacimates id vel, vix et probo decore. Elit legimus fuisset pri at. Vix nibh utamur prodesset ea, ad aliquid facilisi sed, eum dicat assueverit ad. Sea ei volutpat pertinacia, vis te veniam apeirian imperdiet, nam ex ullum cetero luptatum. Mel audire eligendi te. No eum tota definiebas definitionem.", ['ARTS2663', 'MUSC4010', 'MGMT2106'], 63643534234, "tester2", 25, 1)
system.add_group(group)
group.add_user("tester4")
group.add_user("tester6")
group = GroupModel("35", "Group Kathrin", "Location", "Reque ubique feugait eu sit. Duo deleniti apeirian partiendo te, an putent expetenda similique mei, usu accumsan disputationi no. Mea fugit affert ei, et omnis justo aliquid sed. No rebum laboramus sit. Pri laudem labore utroque eu, ad oratio nullam detraxit vix.", ['ECON4307', 'BABS2202', 'BLDG3023'], 63643534234, "tester20", 20, 3)
system.add_group(group)
group.add_user("tester19")
group.add_user("tester1")
group = GroupModel("36", "Group Cordell", "Location", "Reque ubique feugait eu sit. Duo deleniti apeirian partiendo te, an putent expetenda similique mei, usu accumsan disputationi no. Mea fugit affert ei, et omnis justo aliquid sed. No rebum laboramus sit. Pri laudem labore utroque eu, ad oratio nullam detraxit vix.", ['ACCT4809', 'ZEIT3601', 'CVEN4402'], 63643534234, "tester13", 10, 3)
system.add_group(group)
group.add_user("tester16")
group.add_user("tester3")
group = GroupModel("37", "Group Luciana", "Location", "Usu an wisi interpretaris, ei dicat dicant mea. Splendide efficiendi inciderint ea vim, pri amet erant partiendo in. Inermis ocurreret pro at, docendi inciderint ea mei. Te cum homero omnium, per in etiam libris oblique, his tamquam appellantur ex. Vim ut blandit copiosae mediocrem, volumus voluptua adversarium cu eum, ea legere audire mel.", ['ENVS2030', 'MATH3521', 'ZINT2501'], 63643534234, "tester4", 10, 2)
system.add_group(group)
group.add_user("tester8")
group.add_user("tester12")
group = GroupModel("38", "Group Hugh", "Location", "Reque ubique feugait eu sit. Duo deleniti apeirian partiendo te, an putent expetenda similique mei, usu accumsan disputationi no. Mea fugit affert ei, et omnis justo aliquid sed. No rebum laboramus sit. Pri laudem labore utroque eu, ad oratio nullam detraxit vix.", ['ARTS2283', 'AVIA2013', 'SART2361'], 63643534234, "tester14", 5, 2)
system.add_group(group)
group.add_user("tester3")
group.add_user("tester6")
group = GroupModel("39", "Group Neoma", "Location", "Ex iriure nostrum comprehensam sit. Cu cum natum detracto definitiones, meis intellegat elaboraret cu vix. Vim in eirmod partiendo, homero mediocrem reprimique usu et. Vero mutat interpretaris ut nec, oratio mnesarchum omittantur id mei, vel tation ridens adversarium in. Cu clita tempor postea pro. Nam ut dolores persequeris. Animal omittam ut nec.", ['CODE4200', 'GMAT3150', 'GENS4015'], 63643534234, "tester10", 20, 2)
system.add_group(group)
group.add_user("tester14")
group.add_user("tester17")
group = GroupModel("40", "Group Fausto", "Location", "Lorem ipsum dolor sit amet, legendos instructior ius in, quidam tritani labores duo an. Amet blandit elaboraret no vel, sed in homero invenire efficiantur. Ei vix utamur nostrum. Ex alia voluptua senserit pro.", ['BIOM9021', 'SAHT2700', 'ZEIT2602'], 63643534234, "tester6", 15, 1)
system.add_group(group)
group.add_user("tester13")
group.add_user("tester2")
group = GroupModel("41", "Group Lavina", "Location", "Lorem ipsum dolor sit amet, legendos instructior ius in, quidam tritani labores duo an. Amet blandit elaboraret no vel, sed in homero invenire efficiantur. Ei vix utamur nostrum. Ex alia voluptua senserit pro.", ['CVEN4030', 'ARTS4832', 'SART3864'], 63643534234, "tester9", 20, 3)
system.add_group(group)
group.add_user("tester20")
group.add_user("tester18")
group = GroupModel("42", "Group Talia", "Location", "Lorem ipsum dolor sit amet, legendos instructior ius in, quidam tritani labores duo an. Amet blandit elaboraret no vel, sed in homero invenire efficiantur. Ei vix utamur nostrum. Ex alia voluptua senserit pro.", ['ECON3101', 'ZEIT3805', 'CVEN3701'], 63643534234, "tester9", 10, 3)
system.add_group(group)
group.add_user("tester15")
group.add_user("tester8")
group = GroupModel("43", "Group Inell", "Location", "Reque ubique feugait eu sit. Duo deleniti apeirian partiendo te, an putent expetenda similique mei, usu accumsan disputationi no. Mea fugit affert ei, et omnis justo aliquid sed. No rebum laboramus sit. Pri laudem labore utroque eu, ad oratio nullam detraxit vix.", ['LAND2202', 'FOOD1360', 'ARTS3574'], 63643534234, "tester4", 25, 1)
system.add_group(group)
group.add_user("tester17")
group.add_user("tester10")
group = GroupModel("44", "Group Randall", "Location", "Regione accumsan tacimates id vel, vix et probo decore. Elit legimus fuisset pri at. Vix nibh utamur prodesset ea, ad aliquid facilisi sed, eum dicat assueverit ad. Sea ei volutpat pertinacia, vis te veniam apeirian imperdiet, nam ex ullum cetero luptatum. Mel audire eligendi te. No eum tota definiebas definitionem.", ['MMAN2700', 'RISK3002', 'ZPEM1301'], 63643534234, "tester5", 20, 1)
system.add_group(group)
group.add_user("tester16")
group.add_user("tester21")
group = GroupModel("45", "Group Elyse", "Location", "Usu an wisi interpretaris, ei dicat dicant mea. Splendide efficiendi inciderint ea vim, pri amet erant partiendo in. Inermis ocurreret pro at, docendi inciderint ea mei. Te cum homero omnium, per in etiam libris oblique, his tamquam appellantur ex. Vim ut blandit copiosae mediocrem, volumus voluptua adversarium cu eum, ea legere audire mel.", ['INOV2110', 'LAWS2320', 'LAWS3321'], 63643534234, "tester19", 5, 2)
system.add_group(group)
group.add_user("tester6")
group.add_user("tester11")
group = GroupModel("46", "Group Booker", "Location", "Usu an wisi interpretaris, ei dicat dicant mea. Splendide efficiendi inciderint ea vim, pri amet erant partiendo in. Inermis ocurreret pro at, docendi inciderint ea mei. Te cum homero omnium, per in etiam libris oblique, his tamquam appellantur ex. Vim ut blandit copiosae mediocrem, volumus voluptua adversarium cu eum, ea legere audire mel.", ['COMP6733', 'BINF3020', 'SAHT2111'], 63643534234, "tester3", 10, 2)
system.add_group(group)
group.add_user("tester16")
group.add_user("tester3")
group = GroupModel("47", "Group Freddie", "Location", "Regione accumsan tacimates id vel, vix et probo decore. Elit legimus fuisset pri at. Vix nibh utamur prodesset ea, ad aliquid facilisi sed, eum dicat assueverit ad. Sea ei volutpat pertinacia, vis te veniam apeirian imperdiet, nam ex ullum cetero luptatum. Mel audire eligendi te. No eum tota definiebas definitionem.", ['TABL3026', 'MATH2400', 'MUSC4104'], 63643534234, "tester4", 20, 2)
system.add_group(group)
group.add_user("tester14")
group.add_user("tester6")
group = GroupModel("48", "Group Kassandra", "Location", "Est te sanctus placerat eleifend, eam ad legere vituperata accommodare. Te his aeque oporteat corrumpit, has ei noster argumentum. Augue laudem scribentur vel at, eu nisl iudico nusquam quo. Nulla paulo ea per, inermis sadipscing mel ea. An fabulas accusamus ius, ex integre theophrastus sit, ei magna nonumes pro.", ['ZEIT4117', 'ECON2111', 'ZHSS2410'], 63643534234, "tester14", 5, 2)
system.add_group(group)
group.add_user("tester9")
group.add_user("tester16")
group = GroupModel("49", "Group Lavina", "Location", "Agam elitr eos ea. Viderer detraxit mei in, te ferri lobortis reprehendunt per. Vel ex quando graecis apeirian, amet eius quo ea, quas ceteros mel no. Mei eu lorem ullum.", ['LAWS3222', 'SDES2464', 'GMAT1400'], 63643534234, "tester10", 15, 1)
system.add_group(group)
group.add_user("tester16")
group.add_user("tester17")
group = GroupModel("50", "Group Elyse", "Location", "Aliquip iuvaret utroque sed an, vitae graeco voluptaria quo et. Ad iudico mucius quo. Legimus efficiendi eu nec, utroque vulputate ad usu. Mucius facilis ex qui, te quis accusam mel, numquam consectetuer qui ad. Qui iudico platonem te.", ['ZHSS2108', 'BEIL0001', 'COMP9318'], 63643534234, "tester8", 10, 1)
system.add_group(group)
group.add_user("tester14")
group.add_user("tester6")

