from flask import Flask
from flask_restful import Resource, Api
from flask_httpauth import HTTPBasicAuth
from src.system import System
from src.user_model import UserModel
from src.subject import SubjectModel
from src.group_model import GroupModel

app = Flask(__name__)
app.secret_key = "not a secret"
api = Api(app)
auth = HTTPBasicAuth()

system = System()
user = UserModel("first", "last", "tester", "password")
user.add_subject(SubjectModel("HUMS1008", "FL"))
user.add_subject(SubjectModel("FINS3630", "ON"))
user.add_subject(SubjectModel("BIOM9650", "ON"))
user = UserModel("Lyn", "Fager", "tester1", "password")
user.add_subject(SubjectModel("SART2408", "FL"))
user.add_subject(SubjectModel("ZEIT3903", "ON"))
user.add_subject(SubjectModel("AVIA1401", "CR"))
system.add_user(user)
user = UserModel("Pok", "Archambault", "tester2", "password")
user.add_subject(SubjectModel("ZPEM1303", "FL"))
user.add_subject(SubjectModel("MMAN4010", "FL"))
user.add_subject(SubjectModel("MINE2810", "CR"))
system.add_user(user)
user = UserModel("Han", "Monterrosa", "tester3", "password")
user.add_subject(SubjectModel("BABS3151", "DN"))
user.add_subject(SubjectModel("AVEN2230", "CR"))
user.add_subject(SubjectModel("ARTS1060", "ON"))
system.add_user(user)
user = UserModel("Ruthanne", "Millis", "tester4", "password")
user.add_subject(SubjectModel("SOLA5053", "CR"))
user.add_subject(SubjectModel("ZPEM3313", "DN"))
user.add_subject(SubjectModel("MECH4100", "HD"))
system.add_user(user)
user = UserModel("Pok", "Funke", "tester5", "password")
user.add_subject(SubjectModel("ARTS3875", "DN"))
user.add_subject(SubjectModel("GEOS2821", "ON"))
user.add_subject(SubjectModel("SART2403", "HD"))
system.add_user(user)
user = UserModel("Hugh", "Vanriper", "tester6", "password")
user.add_subject(SubjectModel("LAWS3221", "FL"))
user.add_subject(SubjectModel("ARTS3886", "CR"))
user.add_subject(SubjectModel("ZEIT3406", "DN"))
system.add_user(user)
user = UserModel("Inell", "Fillion", "tester7", "password")
user.add_subject(SubjectModel("CRIM4001", "HD"))
user.add_subject(SubjectModel("SDES2116", "FL"))
user.add_subject(SubjectModel("COMP6441", "DN"))
system.add_user(user)
user = UserModel("Jama", "Vizcaino", "tester8", "password")
user.add_subject(SubjectModel("SOMA3416", "HD"))
user.add_subject(SubjectModel("ZHSS2424", "FL"))
user.add_subject(SubjectModel("AVIA3301", "HD"))
system.add_user(user)
user = UserModel("Jeniffer", "Gillum", "tester9", "password")
user.add_subject(SubjectModel("INFS4793", "PS"))
user.add_subject(SubjectModel("ARTS1120", "CR"))
user.add_subject(SubjectModel("LAWS3159", "ON"))
system.add_user(user)
user = UserModel("Hisako", "Abreu", "tester10", "password")
user.add_subject(SubjectModel("TABL2015", "FL"))
user.add_subject(SubjectModel("SAHT3666", "ON"))
user.add_subject(SubjectModel("ZEIT4115", "FL"))
system.add_user(user)
user = UserModel("Jama", "Reiher", "tester11", "password")
user.add_subject(SubjectModel("ZPEM3208", "PS"))
user.add_subject(SubjectModel("CODE2120", "PS"))
user.add_subject(SubjectModel("ARTS2663", "PS"))
system.add_user(user)
user = UserModel("Maxine", "Midgette", "tester12", "password")
user.add_subject(SubjectModel("SOMA2413", "ON"))
user.add_subject(SubjectModel("ARTS3665", "PS"))
user.add_subject(SubjectModel("ARTS2846", "ON"))
system.add_user(user)
user = UserModel("Freddie", "Funke", "tester13", "password")
user.add_subject(SubjectModel("MUSC4103", "HD"))
user.add_subject(SubjectModel("VISN2211", "HD"))
user.add_subject(SubjectModel("ARTS4266", "CR"))
system.add_user(user)
user = UserModel("Kathrin", "Midgette", "tester14", "password")
user.add_subject(SubjectModel("MARK4214", "FL"))
user.add_subject(SubjectModel("CVEN9884", "ON"))
user.add_subject(SubjectModel("ARTS4617", "PS"))
system.add_user(user)
user = UserModel("Tinisha", "Westhoff", "tester15", "password")
user.add_subject(SubjectModel("GEOS3611", "FL"))
user.add_subject(SubjectModel("ARTS2755", "DN"))
user.add_subject(SubjectModel("AVIA1901", "CR"))
system.add_user(user)
user = UserModel("Annis", "Archambault", "tester16", "password")
user.add_subject(SubjectModel("MUSC2701", "ON"))
user.add_subject(SubjectModel("MARK4211", "HD"))
user.add_subject(SubjectModel("LAWS3057", "PS"))
system.add_user(user)
user = UserModel("Carey", "Piner", "tester17", "password")
user.add_subject(SubjectModel("LAWS3165", "HD"))
user.add_subject(SubjectModel("TELE4121", "FL"))
user.add_subject(SubjectModel("SAHT2700", "CR"))
system.add_user(user)
user = UserModel("Reinaldo", "Preece", "tester18", "password")
user.add_subject(SubjectModel("SRAP2001", "DN"))
user.add_subject(SubjectModel("OPTM3231", "CR"))
user.add_subject(SubjectModel("CVEN4901", "DN"))
system.add_user(user)
user = UserModel("Ruthanne", "Piner", "tester19", "password")
user.add_subject(SubjectModel("ACCT4852", "CR"))
user.add_subject(SubjectModel("ADAD4011", "DN"))
user.add_subject(SubjectModel("SDES3404", "CR"))
system.add_user(user)
user = UserModel("Fausto", "Ash", "tester20", "password")
user.add_subject(SubjectModel("ARTS1780", "ON"))
user.add_subject(SubjectModel("PHSL2501", "ON"))
user.add_subject(SubjectModel("ZGEN2240", "ON"))
system.add_user(user)
group = system.create_group("Group Stacie", "Location", "Ex iriure nostrum comprehensam sit. Cu cum natum detracto definitiones, meis intellegat elaboraret cu vix. Vim in eirmod partiendo, homero mediocrem reprimique usu et. Vero mutat interpretaris ut nec, oratio mnesarchum omittantur id mei, vel tation ridens adversarium in. Cu clita tempor postea pro. Nam ut dolores persequeris. Animal omittam ut nec.", ['ARTS3841', 'ARTS1241', 'ATSI2004'], 63643534234, "tester16", 15, 3)
group.add_user("tester4")
group = system.create_group("Group Lyn", "Location", "Est te sanctus placerat eleifend, eam ad legere vituperata accommodare. Te his aeque oporteat corrumpit, has ei noster argumentum. Augue laudem scribentur vel at, eu nisl iudico nusquam quo. Nulla paulo ea per, inermis sadipscing mel ea. An fabulas accusamus ius, ex integre theophrastus sit, ei magna nonumes pro.", ['ZHSS2412', 'MGMT2721', 'MGMT2102'], 63643534234, "tester18", 5, 3)
group.add_user("tester10")
group.add_user("tester8")
group.add_user("tester6")
group.add_user("tester4")
group = system.create_group("Group Regan", "Location", "Aliquip iuvaret utroque sed an, vitae graeco voluptaria quo et. Ad iudico mucius quo. Legimus efficiendi eu nec, utroque vulputate ad usu. Mucius facilis ex qui, te quis accusam mel, numquam consectetuer qui ad. Qui iudico platonem te.", ['ZEIT3121', 'BEIL0010', 'SOCW4003'], 63643534234, "tester8", 10, 3)
group.add_user("tester12")
group = system.create_group("Group Betsy", "Location", "Has mucius meliore percipitur cu, ut vix soluta malorum scripserit. An sit antiopam accommodare, tamquam salutandi liberavisse quo ex. Utroque oportere at ius, vocent nostrud te sit. Te usu soleat voluptua consectetuer. Duo id simul corpora, sed choro perfecto ex, pri id quem alienum.", ['SDES6779', 'PSYC1022', 'SOMA2815'], 63643534234, "tester12", 5, 2)
group.add_user("tester8")
group.add_user("tester6")
group.add_user("tester8")
group = system.create_group("Group Mariam", "Location", "Est te sanctus placerat eleifend, eam ad legere vituperata accommodare. Te his aeque oporteat corrumpit, has ei noster argumentum. Augue laudem scribentur vel at, eu nisl iudico nusquam quo. Nulla paulo ea per, inermis sadipscing mel ea. An fabulas accusamus ius, ex integre theophrastus sit, ei magna nonumes pro.", ['OPTM2111', 'ZEIT4119', 'ARTS2065'], 63643534234, "tester13", 25, 2)
group.add_user("tester20")
group.add_user("tester3")
group.add_user("tester12")
group.add_user("tester10")
group = system.create_group("Group Han", "Location", "Has mucius meliore percipitur cu, ut vix soluta malorum scripserit. An sit antiopam accommodare, tamquam salutandi liberavisse quo ex. Utroque oportere at ius, vocent nostrud te sit. Te usu soleat voluptua consectetuer. Duo id simul corpora, sed choro perfecto ex, pri id quem alienum.", ['ZEIT4901', 'ZHSS1402', 'PSYC1024'], 63643534234, "tester7", 25, 1)
group.add_user("tester18")
group = system.create_group("Group Dannielle", "Location", "In congue delenit splendide mea. Vis probo prompta et, an dignissim mnesarchum eos. Et dicit omnesque postulant nam, habeo delectus eos id, duo movet rationibus in. Eum torquatos assentior instructior te. Eirmod mnesarchum est ad, in purto docendi his. Minim perpetua eos ei, ne tollit percipit pro, ea vel clita decore deterruisset.", ['ARTS1752', 'ZPEM3311', 'PLAN3002'], 63643534234, "tester9", 25, 3)
group.add_user("tester8")
group.add_user("tester15")
group.add_user("tester5")
group.add_user("tester14")
group = system.create_group("Group Adelaida", "Location", "Lorem ipsum dolor sit amet, legendos instructior ius in, quidam tritani labores duo an. Amet blandit elaboraret no vel, sed in homero invenire efficiantur. Ei vix utamur nostrum. Ex alia voluptua senserit pro.", ['ARTS3330', 'CVEN3702', 'BIOM9621'], 63643534234, "tester6", 20, 3)
group.add_user("tester10")
group.add_user("tester15")
group.add_user("tester15")
group = system.create_group("Group Reinaldo", "Location", "Reque ubique feugait eu sit. Duo deleniti apeirian partiendo te, an putent expetenda similique mei, usu accumsan disputationi no. Mea fugit affert ei, et omnis justo aliquid sed. No rebum laboramus sit. Pri laudem labore utroque eu, ad oratio nullam detraxit vix.", ['BEIL6008', 'BEES2041', 'MATH3701'], 63643534234, "tester7", 5, 1)
group.add_user("tester13")
group.add_user("tester7")
group = system.create_group("Group Gaynell", "Location", "Lorem ipsum dolor sit amet, legendos instructior ius in, quidam tritani labores duo an. Amet blandit elaboraret no vel, sed in homero invenire efficiantur. Ei vix utamur nostrum. Ex alia voluptua senserit pro.", ['ZEIT4114', 'MSCI3001', 'ZEIT4301'], 63643534234, "tester5", 5, 2)
group.add_user("tester10")
group = system.create_group("Group Freddie", "Location", "Has mucius meliore percipitur cu, ut vix soluta malorum scripserit. An sit antiopam accommodare, tamquam salutandi liberavisse quo ex. Utroque oportere at ius, vocent nostrud te sit. Te usu soleat voluptua consectetuer. Duo id simul corpora, sed choro perfecto ex, pri id quem alienum.", ['CVEN4300', 'ELEC3705', 'SOLA5054'], 63643534234, "tester11", 15, 1)
group.add_user("tester8")
group.add_user("tester17")
group = system.create_group("Group China", "Location", "Est te sanctus placerat eleifend, eam ad legere vituperata accommodare. Te his aeque oporteat corrumpit, has ei noster argumentum. Augue laudem scribentur vel at, eu nisl iudico nusquam quo. Nulla paulo ea per, inermis sadipscing mel ea. An fabulas accusamus ius, ex integre theophrastus sit, ei magna nonumes pro.", ['ARTS3480', 'LAWS3157', 'LAWS3222'], 63643534234, "tester7", 10, 1)
group.add_user("tester9")
group = system.create_group("Group Tinisha", "Location", "Lorem ipsum dolor sit amet, legendos instructior ius in, quidam tritani labores duo an. Amet blandit elaboraret no vel, sed in homero invenire efficiantur. Ei vix utamur nostrum. Ex alia voluptua senserit pro.", ['ECON2209', 'MATH4001', 'ARTS1453'], 63643534234, "tester11", 20, 1)
group.add_user("tester18")
group = system.create_group("Group Rossie", "Location", "Aliquip iuvaret utroque sed an, vitae graeco voluptaria quo et. Ad iudico mucius quo. Legimus efficiendi eu nec, utroque vulputate ad usu. Mucius facilis ex qui, te quis accusam mel, numquam consectetuer qui ad. Qui iudico platonem te.", ['NAVL4130', 'BABS3121', 'ZEIT1501'], 63643534234, "tester10", 25, 3)
group.add_user("tester5")
group = system.create_group("Group Kassandra", "Location", "Ex iriure nostrum comprehensam sit. Cu cum natum detracto definitiones, meis intellegat elaboraret cu vix. Vim in eirmod partiendo, homero mediocrem reprimique usu et. Vero mutat interpretaris ut nec, oratio mnesarchum omittantur id mei, vel tation ridens adversarium in. Cu clita tempor postea pro. Nam ut dolores persequeris. Animal omittam ut nec.", ['TABL3016', 'CRIM3022', 'ZEIT4297'], 63643534234, "tester20", 15, 3)
group.add_user("tester7")
group.add_user("tester9")
group.add_user("tester11")
group.add_user("tester12")
group = system.create_group("Group Hisako", "Location", "Aliquip iuvaret utroque sed an, vitae graeco voluptaria quo et. Ad iudico mucius quo. Legimus efficiendi eu nec, utroque vulputate ad usu. Mucius facilis ex qui, te quis accusam mel, numquam consectetuer qui ad. Qui iudico platonem te.", ['ZBUS2207', 'COMP3161', 'ZPEM3313'], 63643534234, "tester13", 20, 3)
group.add_user("tester13")
group.add_user("tester11")
group.add_user("tester11")
group.add_user("tester17")
group = system.create_group("Group Jama", "Location", "Aliquip iuvaret utroque sed an, vitae graeco voluptaria quo et. Ad iudico mucius quo. Legimus efficiendi eu nec, utroque vulputate ad usu. Mucius facilis ex qui, te quis accusam mel, numquam consectetuer qui ad. Qui iudico platonem te.", ['ZEIT3603', 'MTRN3200', 'ARTS4829'], 63643534234, "tester3", 15, 1)
group.add_user("tester18")
group.add_user("tester13")
group.add_user("tester20")
group = system.create_group("Group Jama", "Location", "Lorem ipsum dolor sit amet, legendos instructior ius in, quidam tritani labores duo an. Amet blandit elaboraret no vel, sed in homero invenire efficiantur. Ei vix utamur nostrum. Ex alia voluptua senserit pro.", ['ELEC3705', 'ARTS1844', 'SOMA2605'], 63643534234, "tester16", 15, 3)
group.add_user("tester1")
group.add_user("tester11")
group = system.create_group("Group Jacquelyn", "Location", "Regione accumsan tacimates id vel, vix et probo decore. Elit legimus fuisset pri at. Vix nibh utamur prodesset ea, ad aliquid facilisi sed, eum dicat assueverit ad. Sea ei volutpat pertinacia, vis te veniam apeirian imperdiet, nam ex ullum cetero luptatum. Mel audire eligendi te. No eum tota definiebas definitionem.", ['ARTS3633', 'ZEIT4225', 'ARTS3061'], 63643534234, "tester7", 10, 1)
group.add_user("tester17")
group.add_user("tester5")
group.add_user("tester15")
group = system.create_group("Group Shira", "Location", "Usu an wisi interpretaris, ei dicat dicant mea. Splendide efficiendi inciderint ea vim, pri amet erant partiendo in. Inermis ocurreret pro at, docendi inciderint ea mei. Te cum homero omnium, per in etiam libris oblique, his tamquam appellantur ex. Vim ut blandit copiosae mediocrem, volumus voluptua adversarium cu eum, ea legere audire mel.", ['SAHT1101', 'ATSI3008', 'MATS5003'], 63643534234, "tester3", 10, 2)
group.add_user("tester2")
group.add_user("tester13")
group.add_user("tester13")
group.add_user("tester17")
group = system.create_group("Group Han", "Location", "Aliquip iuvaret utroque sed an, vitae graeco voluptaria quo et. Ad iudico mucius quo. Legimus efficiendi eu nec, utroque vulputate ad usu. Mucius facilis ex qui, te quis accusam mel, numquam consectetuer qui ad. Qui iudico platonem te.", ['ZEIT1503', 'INTA2301', 'ZEIT2307'], 63643534234, "tester19", 15, 3)
group.add_user("tester18")
group.add_user("tester18")
group.add_user("tester21")
group = system.create_group("Group Hisako", "Location", "Est te sanctus placerat eleifend, eam ad legere vituperata accommodare. Te his aeque oporteat corrumpit, has ei noster argumentum. Augue laudem scribentur vel at, eu nisl iudico nusquam quo. Nulla paulo ea per, inermis sadipscing mel ea. An fabulas accusamus ius, ex integre theophrastus sit, ei magna nonumes pro.", ['BIOM5910', 'PSYC1022', 'ZEIT4113'], 63643534234, "tester14", 20, 3)
group.add_user("tester18")
group.add_user("tester2")
group.add_user("tester21")
group.add_user("tester10")
group = system.create_group("Group Freddie", "Location", "In congue delenit splendide mea. Vis probo prompta et, an dignissim mnesarchum eos. Et dicit omnesque postulant nam, habeo delectus eos id, duo movet rationibus in. Eum torquatos assentior instructior te. Eirmod mnesarchum est ad, in purto docendi his. Minim perpetua eos ei, ne tollit percipit pro, ea vel clita decore deterruisset.", ['MDIA2007', 'ARCH1482', 'LAWS2384'], 63643534234, "tester9", 15, 1)
group.add_user("tester4")
group = system.create_group("Group Jacquelyn", "Location", "Aliquip iuvaret utroque sed an, vitae graeco voluptaria quo et. Ad iudico mucius quo. Legimus efficiendi eu nec, utroque vulputate ad usu. Mucius facilis ex qui, te quis accusam mel, numquam consectetuer qui ad. Qui iudico platonem te.", ['PSYC3311', 'ARTS4823', 'ELEC2134'], 63643534234, "tester1", 15, 3)
group.add_user("tester4")
group.add_user("tester20")
group.add_user("tester7")
group.add_user("tester1")
group = system.create_group("Group Neoma", "Location", "Regione accumsan tacimates id vel, vix et probo decore. Elit legimus fuisset pri at. Vix nibh utamur prodesset ea, ad aliquid facilisi sed, eum dicat assueverit ad. Sea ei volutpat pertinacia, vis te veniam apeirian imperdiet, nam ex ullum cetero luptatum. Mel audire eligendi te. No eum tota definiebas definitionem.", ['CVEN9405', 'BEIL0008', 'ZPEM3103'], 63643534234, "tester19", 25, 1)
group.add_user("tester14")
group = system.create_group("Group Reanna", "Location", "Regione accumsan tacimates id vel, vix et probo decore. Elit legimus fuisset pri at. Vix nibh utamur prodesset ea, ad aliquid facilisi sed, eum dicat assueverit ad. Sea ei volutpat pertinacia, vis te veniam apeirian imperdiet, nam ex ullum cetero luptatum. Mel audire eligendi te. No eum tota definiebas definitionem.", ['ARTS2213', 'SDES3172', 'LAWS3182'], 63643534234, "tester4", 5, 1)
group.add_user("tester21")
group.add_user("tester12")
group = system.create_group("Group Lyn", "Location", "Est te sanctus placerat eleifend, eam ad legere vituperata accommodare. Te his aeque oporteat corrumpit, has ei noster argumentum. Augue laudem scribentur vel at, eu nisl iudico nusquam quo. Nulla paulo ea per, inermis sadipscing mel ea. An fabulas accusamus ius, ex integre theophrastus sit, ei magna nonumes pro.", ['TABL2741', 'EDST6778', 'PHYS4949'], 63643534234, "tester2", 5, 3)
group.add_user("tester18")
group = system.create_group("Group Carey", "Location", "Est te sanctus placerat eleifend, eam ad legere vituperata accommodare. Te his aeque oporteat corrumpit, has ei noster argumentum. Augue laudem scribentur vel at, eu nisl iudico nusquam quo. Nulla paulo ea per, inermis sadipscing mel ea. An fabulas accusamus ius, ex integre theophrastus sit, ei magna nonumes pro.", ['MATH4803', 'EDST6752', 'MDIA2010'], 63643534234, "tester3", 15, 3)
group.add_user("tester15")
group.add_user("tester4")
group.add_user("tester14")
group.add_user("tester4")
group = system.create_group("Group Annis", "Location", "Lorem ipsum dolor sit amet, legendos instructior ius in, quidam tritani labores duo an. Amet blandit elaboraret no vel, sed in homero invenire efficiantur. Ei vix utamur nostrum. Ex alia voluptua senserit pro.", ['ARTS4916', 'PSYC3331', 'LAND1421'], 63643534234, "tester2", 15, 3)
group.add_user("tester13")
group.add_user("tester7")
group.add_user("tester2")
group = system.create_group("Group Lavina", "Location", "Aliquip iuvaret utroque sed an, vitae graeco voluptaria quo et. Ad iudico mucius quo. Legimus efficiendi eu nec, utroque vulputate ad usu. Mucius facilis ex qui, te quis accusam mel, numquam consectetuer qui ad. Qui iudico platonem te.", ['SDES0010', 'ARTS4813', 'MUSC4014'], 63643534234, "tester7", 25, 1)
group.add_user("tester11")
group.add_user("tester8")
group = system.create_group("Group Lyn", "Location", "Lorem ipsum dolor sit amet, legendos instructior ius in, quidam tritani labores duo an. Amet blandit elaboraret no vel, sed in homero invenire efficiantur. Ei vix utamur nostrum. Ex alia voluptua senserit pro.", ['BIOC4428', 'CRIM4004', 'ZPEM3532'], 63643534234, "tester13", 10, 2)
group.add_user("tester6")
group = system.create_group("Group Elyse", "Location", "Ex iriure nostrum comprehensam sit. Cu cum natum detracto definitiones, meis intellegat elaboraret cu vix. Vim in eirmod partiendo, homero mediocrem reprimique usu et. Vero mutat interpretaris ut nec, oratio mnesarchum omittantur id mei, vel tation ridens adversarium in. Cu clita tempor postea pro. Nam ut dolores persequeris. Animal omittam ut nec.", ['INFS2101', 'BLDG4285', 'MATS4003'], 63643534234, "tester16", 5, 1)
group.add_user("tester14")
group.add_user("tester14")
group = system.create_group("Group Betsy", "Location", "Has mucius meliore percipitur cu, ut vix soluta malorum scripserit. An sit antiopam accommodare, tamquam salutandi liberavisse quo ex. Utroque oportere at ius, vocent nostrud te sit. Te usu soleat voluptua consectetuer. Duo id simul corpora, sed choro perfecto ex, pri id quem alienum.", ['MFAC2506', 'CVEN2401', 'FOOD5400'], 63643534234, "tester14", 15, 1)
group.add_user("tester21")
group.add_user("tester19")
group.add_user("tester20")
group = system.create_group("Group Jama", "Location", "In congue delenit splendide mea. Vis probo prompta et, an dignissim mnesarchum eos. Et dicit omnesque postulant nam, habeo delectus eos id, duo movet rationibus in. Eum torquatos assentior instructior te. Eirmod mnesarchum est ad, in purto docendi his. Minim perpetua eos ei, ne tollit percipit pro, ea vel clita decore deterruisset.", ['FOOD4403', 'ZEIT1901', 'ZEIT4013'], 63643534234, "tester3", 20, 1)
group.add_user("tester20")
group.add_user("tester20")
group.add_user("tester15")
group.add_user("tester16")
group = system.create_group("Group Annis", "Location", "Ex iriure nostrum comprehensam sit. Cu cum natum detracto definitiones, meis intellegat elaboraret cu vix. Vim in eirmod partiendo, homero mediocrem reprimique usu et. Vero mutat interpretaris ut nec, oratio mnesarchum omittantur id mei, vel tation ridens adversarium in. Cu clita tempor postea pro. Nam ut dolores persequeris. Animal omittam ut nec.", ['ELEC2141', 'LAWS2820', 'COMP1000'], 63643534234, "tester4", 20, 3)
group.add_user("tester20")
group = system.create_group("Group Jacquelyn", "Location", "Usu an wisi interpretaris, ei dicat dicant mea. Splendide efficiendi inciderint ea vim, pri amet erant partiendo in. Inermis ocurreret pro at, docendi inciderint ea mei. Te cum homero omnium, per in etiam libris oblique, his tamquam appellantur ex. Vim ut blandit copiosae mediocrem, volumus voluptua adversarium cu eum, ea legere audire mel.", ['FOOD2350', 'SOMA1642', 'SOMA3410'], 63643534234, "tester5", 20, 2)
group.add_user("tester21")
group.add_user("tester21")
group = system.create_group("Group Dannielle", "Location", "Lorem ipsum dolor sit amet, legendos instructior ius in, quidam tritani labores duo an. Amet blandit elaboraret no vel, sed in homero invenire efficiantur. Ei vix utamur nostrum. Ex alia voluptua senserit pro.", ['EDST6716', 'MUSC1706', 'VISN1101'], 63643534234, "tester17", 25, 2)
group.add_user("tester11")
group = system.create_group("Group Annis", "Location", "In congue delenit splendide mea. Vis probo prompta et, an dignissim mnesarchum eos. Et dicit omnesque postulant nam, habeo delectus eos id, duo movet rationibus in. Eum torquatos assentior instructior te. Eirmod mnesarchum est ad, in purto docendi his. Minim perpetua eos ei, ne tollit percipit pro, ea vel clita decore deterruisset.", ['PHCM3003', 'ARTS1091', 'EDST6724'], 63643534234, "tester20", 15, 2)
group.add_user("tester15")
group.add_user("tester1")
group.add_user("tester2")
group.add_user("tester8")
group = system.create_group("Group Mariam", "Location", "Has mucius meliore percipitur cu, ut vix soluta malorum scripserit. An sit antiopam accommodare, tamquam salutandi liberavisse quo ex. Utroque oportere at ius, vocent nostrud te sit. Te usu soleat voluptua consectetuer. Duo id simul corpora, sed choro perfecto ex, pri id quem alienum.", ['COMM2222', 'LAWS1021', 'LAWS3017'], 63643534234, "tester13", 10, 3)
group.add_user("tester7")
group = system.create_group("Group Lili", "Location", "Agam elitr eos ea. Viderer detraxit mei in, te ferri lobortis reprehendunt per. Vel ex quando graecis apeirian, amet eius quo ea, quas ceteros mel no. Mei eu lorem ullum.", ['LAWS3276', 'ARTS3063', 'COMP6445'], 63643534234, "tester3", 5, 1)
group.add_user("tester9")
group.add_user("tester15")
group.add_user("tester2")
group = system.create_group("Group Owen", "Location", "Usu an wisi interpretaris, ei dicat dicant mea. Splendide efficiendi inciderint ea vim, pri amet erant partiendo in. Inermis ocurreret pro at, docendi inciderint ea mei. Te cum homero omnium, per in etiam libris oblique, his tamquam appellantur ex. Vim ut blandit copiosae mediocrem, volumus voluptua adversarium cu eum, ea legere audire mel.", ['MATS4004', 'ELEC4622', 'INFS2631'], 63643534234, "tester12", 20, 2)
group.add_user("tester13")
group.add_user("tester10")
group.add_user("tester5")
group = system.create_group("Group Lavina", "Location", "Regione accumsan tacimates id vel, vix et probo decore. Elit legimus fuisset pri at. Vix nibh utamur prodesset ea, ad aliquid facilisi sed, eum dicat assueverit ad. Sea ei volutpat pertinacia, vis te veniam apeirian imperdiet, nam ex ullum cetero luptatum. Mel audire eligendi te. No eum tota definiebas definitionem.", ['ZEIT1206', 'MANF4450', 'ARTS2660'], 63643534234, "tester14", 25, 3)
group.add_user("tester14")
group.add_user("tester16")
group = system.create_group("Group Jama", "Location", "Agam elitr eos ea. Viderer detraxit mei in, te ferri lobortis reprehendunt per. Vel ex quando graecis apeirian, amet eius quo ea, quas ceteros mel no. Mei eu lorem ullum.", ['MUSC3808', 'ARTS1210', 'ARTS4838'], 63643534234, "tester19", 25, 1)
group.add_user("tester7")
group = system.create_group("Group Patty", "Location", "In congue delenit splendide mea. Vis probo prompta et, an dignissim mnesarchum eos. Et dicit omnesque postulant nam, habeo delectus eos id, duo movet rationibus in. Eum torquatos assentior instructior te. Eirmod mnesarchum est ad, in purto docendi his. Minim perpetua eos ei, ne tollit percipit pro, ea vel clita decore deterruisset.", ['SART3800', 'PSYC1023', 'ELEC1112'], 63643534234, "tester8", 15, 3)
group.add_user("tester12")
group.add_user("tester4")
group = system.create_group("Group Thresa", "Location", "Aliquip iuvaret utroque sed an, vitae graeco voluptaria quo et. Ad iudico mucius quo. Legimus efficiendi eu nec, utroque vulputate ad usu. Mucius facilis ex qui, te quis accusam mel, numquam consectetuer qui ad. Qui iudico platonem te.", ['COMP3211', 'ELEC4121', 'SCIF1111'], 63643534234, "tester4", 25, 3)
group.add_user("tester15")
group.add_user("tester1")
group = system.create_group("Group Mariam", "Location", "In congue delenit splendide mea. Vis probo prompta et, an dignissim mnesarchum eos. Et dicit omnesque postulant nam, habeo delectus eos id, duo movet rationibus in. Eum torquatos assentior instructior te. Eirmod mnesarchum est ad, in purto docendi his. Minim perpetua eos ei, ne tollit percipit pro, ea vel clita decore deterruisset.", ['INST1005', 'ARTS4821', 'EDST2003'], 63643534234, "tester15", 25, 2)
group.add_user("tester14")
group = system.create_group("Group Maxine", "Location", "Has mucius meliore percipitur cu, ut vix soluta malorum scripserit. An sit antiopam accommodare, tamquam salutandi liberavisse quo ex. Utroque oportere at ius, vocent nostrud te sit. Te usu soleat voluptua consectetuer. Duo id simul corpora, sed choro perfecto ex, pri id quem alienum.", ['ARTS1090', 'GENL2015', 'IDES3231'], 63643534234, "tester9", 25, 3)
group.add_user("tester20")
group.add_user("tester6")
group = system.create_group("Group Lyn", "Location", "Lorem ipsum dolor sit amet, legendos instructior ius in, quidam tritani labores duo an. Amet blandit elaboraret no vel, sed in homero invenire efficiantur. Ei vix utamur nostrum. Ex alia voluptua senserit pro.", ['COMM3030', 'PHYS1110', 'ZEIT3903'], 63643534234, "tester14", 15, 3)
group.add_user("tester11")
group.add_user("tester11")
group.add_user("tester3")
group = system.create_group("Group Neoma", "Location", "Lorem ipsum dolor sit amet, legendos instructior ius in, quidam tritani labores duo an. Amet blandit elaboraret no vel, sed in homero invenire efficiantur. Ei vix utamur nostrum. Ex alia voluptua senserit pro.", ['INFS3692', 'EDST6706', 'TABL3040'], 63643534234, "tester6", 20, 2)
group.add_user("tester8")
group.add_user("tester8")
group = system.create_group("Group Luciana", "Location", "Est te sanctus placerat eleifend, eam ad legere vituperata accommodare. Te his aeque oporteat corrumpit, has ei noster argumentum. Augue laudem scribentur vel at, eu nisl iudico nusquam quo. Nulla paulo ea per, inermis sadipscing mel ea. An fabulas accusamus ius, ex integre theophrastus sit, ei magna nonumes pro.", ['AVIA2014', 'MGMT3724', 'MGMT2704'], 63643534234, "tester6", 20, 3)
group.add_user("tester12")
group.add_user("tester20")
group.add_user("tester17")
group.add_user("tester18")

